version: '3'

services:
  app:
    build: .
    ports:
      - "80:80"
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./prerender.json:/app/prerender.json
      - ./server.js:/app/server.js
    command: node server.js