server {
    listen 80;
    server_name _;

    location = / {
        return 302 /administrador/;
    }

    location /administrador/ {
        alias /usr/share/nginx/html/administrador/;
        try_files $uri $uri/ /administrador/index.html;
    }
}
