server {
    listen 80;
    server_name _;

    location = / {
        return 302 /administrador/;
    }

    location /administrador/assets/ {
        alias /usr/share/nginx/html/administrador/assets/;
        access_log off;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location /administrador/ {
        alias /usr/share/nginx/html/administrador/;
        index index.html;
        try_files $uri $uri/ /administrador/index.html;
    }
}
